apiVersion: batch/v1
kind: CronJob
metadata:
  name: transaction-etl
  namespace: dataops-hub
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: etl
            image: dataops-hub-etl:latest
            resources:
              requests:
                memory: "4Gi"
                cpu: "2"
              limits:
                memory: "8Gi"
                cpu: "4"
            env:
            - name: AWS_REGION
              value: eu-central-1
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-credentials
                  key: secret-access-key
          restartPolicy: OnFailure
---
apiVersion: v1
kind: Namespace
metadata:
  name: dataops-hub
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials
  namespace: dataops-hub
type: Opaque
data:
  # These values should be base64 encoded
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_ACCESS_KEY} 