name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Add permissions needed for OIDC
permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  TERRAFORM_VERSION: 1.4.6

jobs:
  test:
    if: contains(github.event.head_commit.message, '[skip test]') == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-binary :all: pandas numpy
        pip install -r requirements.txt
        pip install -r dev-requirements.txt

    - name: Run linters
      run: |
        black --check .
        isort --check-only .
        mypy src/

    - name: Run tests
      run: |
        pytest --cov=src tests/

  terraform:
    needs: test
    if: |
      always() &&
      (needs.test.result == 'success' || needs.test.result == 'skipped') &&
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Check Terraform Formatting
      working-directory: ./terraform
      run: |
        terraform fmt -check -recursive
        if [ $? -ne 0 ]; then
          echo "Error: Terraform files are not properly formatted. Run 'terraform fmt' to fix."
          exit 1
        fi

    - name: Terraform Plan
      working-directory: ./terraform
      run: terraform plan -input=false

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      working-directory: ./terraform
      run: terraform apply -auto-approve -input=false

  deploy:
    needs: terraform
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install --no-binary :all: pandas numpy
        pip install -r requirements.txt

    - name: Generate and Load Data
      run: python src/data_generator/generate_data.py 