name: Terraform Destroy

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: 'Type "DESTROY-PRODUCTION" to confirm deletion of all resources'
        required: true
        type: string

# Prevent concurrent destroy operations
concurrency: 
  group: terraform-destroy
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-central-1
  TERRAFORM_VERSION: 1.4.6

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'DESTROY-PRODUCTION'
    environment: production
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Plan Destroy
      working-directory: ./terraform
      run: |
        echo "🔍 Planning destruction of all resources..."
        terraform plan -destroy -out=destroy.tfplan
      
    - name: Final Warning
      run: |
        echo "⚠️ DANGER: You are about to destroy all resources in PRODUCTION ⚠️"
        echo "Resources that will be destroyed:"
        echo "- RDS Aurora PostgreSQL Cluster and Instances"
        echo "- VPC and all networking components"
        echo "- Security Groups"
        echo "- S3 Buckets"
        echo "- Secrets Manager Secrets"
        echo ""
        echo "Waiting 30 seconds before destruction begins..."
        sleep 30

    - name: Terraform Destroy
      working-directory: ./terraform
      run: |
        echo "💥 Beginning destruction of resources..."
        terraform apply -auto-approve destroy.tfplan
        echo "✅ All resources have been destroyed." 